// seed.mjs - 137 KPI'yı Supabase'e aktarır
// Çalıştır: node scripts/seed.mjs

import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// .env.local'dan oku
const envPath = join(__dirname, "..", ".env.local");
const env = Object.fromEntries(
  readFileSync(envPath, "utf-8")
    .split("\n")
    .filter((l) => l.includes("="))
    .map((l) => l.split("=").map((p) => p.trim()))
);

const supabase = createClient(
  env["NEXT_PUBLIC_SUPABASE_URL"],
  env["SUPABASE_SERVICE_ROLE_KEY"]
);

const KPI_DATA = [
  { indicator_name: "Bakım taleplerinin ortalama kapanma süresi", indicator_definition: "Operatörlerin ilettiği bakım arıza taleplerinin ne kadar sürede sonuçlandırıldığı takip edilir.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Bakım", related_other_process: "", indicator_tag: "Arıza, Bakım Yönetimi", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Belirlenen hedeflerin dışındaki KPI'ların yüzdesi", indicator_definition: "Belirlenen amaçların/hedeflerin dışında kalan (yani \"kırmızı\" olan) Temel Performans Göstergelerinin (KPI'lar) ölçümlerine göre yüzdesi.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Kalite", related_other_process: "", indicator_tag: "KPI, Gösterge", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Bordro ödeme hatası sayısı", indicator_definition: "Bordro ödeme hatalarının sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Bordo, İK, Maaş", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çalışan başına CO2 Ton", indicator_definition: "Çalışan başına düşen karbondioksit emisyonunu ölçer. Bu KPI, şirketin çevresel ayak izini takip etmeye ve azaltmaya yardımcı olur.", direction: "Azalması İyi", measurement: "Ton", related_process: "Çevre", related_other_process: "", indicator_tag: "CO2, Çevre, Emisyon, Karbon", indicator_related_management_system: "ISO 14001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çalışan başına gelir", indicator_definition: "Toplam gelirin çalışan sayısına bölünmesiyle hesaplanan bir verimlilik metriğidir.", direction: "Artması İyi", measurement: "Para", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Gelir, İK, Verimlilik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çalışan devamsızlık oranı", indicator_definition: "Devamsızlık Oranı = (Devamsızlık Günleri / (Toplam Çalışan Sayısı x Toplam İş Günleri)) x 100", direction: "Azalması İyi", measurement: "Yüzde", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Devamsızlık, İK", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çalışan memnuniyeti endeksi", indicator_definition: "Çalışanların işlerinden ne kadar memnun olduklarını ölçen bir endeks.", direction: "Artması İyi", measurement: "Puan", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Memnuniyet, İK, Çalışan", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çalışan başına eğitim saati", indicator_definition: "Şirketin çalışan başına verdiği eğitim saatinin ölçülmesidir.", direction: "Artması İyi", measurement: "Zaman", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Eğitim, İK", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çalışan işten ayrılma oranı", indicator_definition: "Belirli bir dönemde şirketten ayrılan çalışanların toplam çalışan sayısına oranıdır.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "İşten Ayrılma, İK, Devir Oranı", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çevresel uyumsuzluk sayısı", indicator_definition: "Çevresel uyumsuzlukların sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Çevre", related_other_process: "", indicator_tag: "Çevre, Uyumsuzluk", indicator_related_management_system: "ISO 14001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Denetim bulgusu sayısı", indicator_definition: "İç ve dış denetimler sonucunda tespit edilen uygunsuzluk ve gözlem sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Kalite", related_other_process: "", indicator_tag: "Denetim, Uygunsuzluk, İç Denetim", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Dönem sonu stok seviyesi", indicator_definition: "Dönem sonunda elde bulunan stok miktarı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Stok, Tedarik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ekipman kullanım oranı", indicator_definition: "Ekipmanın toplam kullanılabilir süre içinde fiilen kullanıldığı sürenin yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Üretim", related_other_process: "", indicator_tag: "Ekipman, OEE, Kullanım", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Fatura Başına Maliyet, Tedarikçi", indicator_definition: "Her bir tedarikçi faturasının işlenmesi için harcanan ortalama maliyet.", direction: "Azalması İyi", measurement: "Para", related_process: "Finans", related_other_process: "", indicator_tag: "Fatura, Maliyet, Tedarik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Genel ekipman etkinliği (OEE)", indicator_definition: "OEE = Kullanılabilirlik x Performans x Kalite", direction: "Artması İyi", measurement: "Yüzde", related_process: "Üretim", related_other_process: "", indicator_tag: "OEE, Ekipman, Üretim", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Güvenlik olayı sayısı", indicator_definition: "Belirli bir dönemde meydana gelen iş kazası veya güvenlik olayı sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "", indicator_tag: "Kaza, İSG, Güvenlik", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Hata oranı", indicator_definition: "Üretim sürecinde ortaya çıkan hata sayısının toplam üretim adedine oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Kalite", related_other_process: "", indicator_tag: "Hata, Kalite, Üretim", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İade edilen ürünlerin yüzdesi", indicator_definition: "Müşteri tarafından iade edilen ürünlerin toplam satılan ürünlere oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "İade, Müşteri, Satış", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İlk seferde doğru üretim oranı (FTT)", indicator_definition: "Yeniden işleme veya onarım yapılmadan ilk seferinde hatasız üretilen parçaların yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Kalite", related_other_process: "", indicator_tag: "FTT, Kalite, Üretim", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İşe alım süresi", indicator_definition: "Bir pozisyonun açılmasından başvuranın işe kabul edilmesine kadar geçen ortalama süre.", direction: "Azalması İyi", measurement: "Zaman", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "İşe Alım, İK, Süre", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "ISO 9001 iç denetimde minör bulgu sayısı", indicator_definition: "ISO 9001 iç denetimlerinde tespit edilen minör (küçük) uygunsuzluk sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Kalite", related_other_process: "", indicator_tag: "ISO 9001, Denetim, Kalite", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Karlılık oranı", indicator_definition: "Net karın toplam gelire oranıdır.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Finans", related_other_process: "", indicator_tag: "Karlılık, Finans, Gelir", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Kar Marjı, Gerçek", indicator_definition: "Gerçekleşen kar marjının yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Finans", related_other_process: "", indicator_tag: "Kar Marjı, Finans", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Kritik ekipman arıza süresi", indicator_definition: "Kritik üretim ekipmanlarının arıza nedeniyle duraklatıldığı toplam süre.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Bakım", related_other_process: "", indicator_tag: "Arıza, Bakım, Ekipman", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Kullanılmayan izin günleri", indicator_definition: "Çalışanların kullanmadığı kümülatif izin günleri.", direction: "Azalması İyi", measurement: "Zaman", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "İzin, İK", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Lojistik maliyet oranı", indicator_definition: "Toplam lojistik maliyetinin toplam satışlara oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Lojistik, Maliyet, Tedarik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Malzeme fire oranı", indicator_definition: "Üretim sürecinde kullanılmayan veya bozulan malzeme miktarının toplam kullanılan malzeme miktarına oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Üretim", related_other_process: "", indicator_tag: "Fire, Malzeme, Üretim", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Marka bilinirlik oranı", indicator_definition: "Hedef pazar içinde markanızı tanıyan kişilerin oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Marka, Pazarlama, Bilinirlik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Mevcut çalışan oranı", indicator_definition: "Aktif çalışan sayısının toplam işgücü kapasitesine oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Çalışan, İK, Kapasite", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Müşteri başına gelir", indicator_definition: "Belirli bir dönemde her bir müşteriden elde edilen ortalama gelir.", direction: "Artması İyi", measurement: "Para", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Müşteri, Gelir, Satış", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Müşteri kayıp oranı", indicator_definition: "Belirli bir dönemde şirketle ilişkisini kesen müşteri yüzdesi.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Müşteri, Kayıp, Satış", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Müşteri memnuniyet skoru (CSAT)", indicator_definition: "Müşterilerin ürün veya hizmetten duydukları memnuniyeti ölçen puan.", direction: "Artması İyi", measurement: "Puan", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "CSAT, Müşteri Memnuniyeti", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Müşteri şikayet sayısı", indicator_definition: "Belirli bir dönemde alınan müşteri şikayet sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Satış ve Pazarlama", related_other_process: "Kalite", indicator_tag: "Şikayet, Müşteri, Kalite", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Net Tavsiye Skoru (NPS)", indicator_definition: "Müşterilerin bir ürünü veya hizmeti başkalarına tavsiye etme olasılığını ölçen metriktir.", direction: "Artması İyi", measurement: "Puan", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "NPS, Müşteri, Tavsiye", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Onboarding süresi", indicator_definition: "Yeni bir çalışanın tam üretkenliğe ulaşması için geçen süre.", direction: "Azalması İyi", measurement: "Zaman", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Onboarding, İK, Oryantasyon", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ortalama bakım maliyeti", indicator_definition: "Belirli bir dönemde gerçekleştirilen bakım faaliyetlerinin ortalama maliyeti.", direction: "Azalması İyi", measurement: "Para", related_process: "Bakım", related_other_process: "", indicator_tag: "Bakım, Maliyet", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ortalama kurtarma süresi (MTTR)", indicator_definition: "Bir arızanın tespit edilmesinden tamamen giderilmesine kadar geçen ortalama süre.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Bakım", related_other_process: "", indicator_tag: "MTTR, Bakım, Arıza", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ortalama olay çözüm süresi", indicator_definition: "IT destek taleplerinin veya olaylarının ortalama çözüm süresi.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "IT, Helpdesk, Çözüm Süresi", indicator_related_management_system: "ISO 27001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ortalama sipariş değeri", indicator_definition: "Belirli bir dönemdeki toplam gelirin sipariş sayısına bölünmesiyle elde edilen ortalama sipariş değeri.", direction: "Artması İyi", measurement: "Para", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Sipariş, Satış, Gelir", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ortalama süre arızalar arası (MTBF)", indicator_definition: "İki ardışık arıza arasında geçen ortalama süre.", direction: "Artması İyi", measurement: "Zaman", related_process: "Bakım", related_other_process: "", indicator_tag: "MTBF, Bakım, Güvenilirlik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Planlı bakım oranı", indicator_definition: "Toplam bakım faaliyetleri içinde planlı (önleyici) bakımların yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Bakım", related_other_process: "", indicator_tag: "Bakım, Planlı Bakım", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Proje tamamlanma oranı", indicator_definition: "Belirlenen süre ve bütçe içinde tamamlanan projelerin toplam projelere oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Arge", related_other_process: "", indicator_tag: "Proje, Ar-Ge, Tamamlama", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "R&D harcamalarının gelire oranı", indicator_definition: "Araştırma ve geliştirme harcamalarının toplam gelire oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Arge", related_other_process: "", indicator_tag: "Ar-Ge, Harcama, İnovasyon", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Satış başarı oranı", indicator_definition: "Kazanılan fırsatların toplam fırsatlara oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Satış, Başarı, CRM", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Satış büyüme oranı", indicator_definition: "Belirli bir dönemdeki satışların bir önceki döneme göre artış yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Satış, Büyüme, Gelir", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Sipariş karşılama oranı", indicator_definition: "Zamanında ve eksiksiz karşılanan siparişlerin toplam siparişlere oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Sipariş, Teslimat, Tedarik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Sistem kullanılabilirlik oranı (Uptime)", indicator_definition: "Bir IT sisteminin toplam planlı çalışma süresi içinde gerçekten çalışır durumda olduğu sürenin yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "Uptime, IT, Sistem", indicator_related_management_system: "ISO 27001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "SLA başına ortalama ceza maliyetleri", indicator_definition: "SLA ihlalleri nedeniyle ödenen ortalama ceza maliyeti.", direction: "Azalması İyi", measurement: "Para", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "SLA, IT, Ceza", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Stok devir hızı", indicator_definition: "Bir işletmenin stoklarını belirli bir dönemde kaç kez sattığını veya kullandığını gösteren oran.", direction: "Artması İyi", measurement: "Sayı", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Stok, Devir, Tedarik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Stok doğruluk oranı", indicator_definition: "Fiili stok miktarının sistemdeki stok kaydıyla uyumlu olma oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Stok, Doğruluk, Sayım", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Tedarik döngü süresi", indicator_definition: "Satın alma talebinin oluşturulmasından malın alınmasına kadar geçen ortalama süre.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Tedarik, Süre, Satın Alma", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Tedarikçi değerlendirme skoru", indicator_definition: "Tedarikçilerin kalite, teslimat, fiyat ve hizmet gibi kriterlere göre değerlendirilmesi.", direction: "Artması İyi", measurement: "Puan", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Tedarikçi, Değerlendirme, Kalite", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Tedarikçi zamanında teslimat oranı", indicator_definition: "Tedarikçilerin siparişleri zamanında teslim etme yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Tedarikçi, Teslimat, Zamanında", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Toplam recordable kaza oranı (TRIR)", indicator_definition: "100 tam zamanlı çalışan başına düşen kayıt altına alınan kaza sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "", indicator_tag: "TRIR, Kaza, İSG", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Üretim çevrim süresi", indicator_definition: "Bir ürünün üretim sürecinde başlangıçtan bitişe kadar geçen toplam süre.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Üretim", related_other_process: "", indicator_tag: "Çevrim Süresi, Üretim", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Üretim planına uyum oranı", indicator_definition: "Gerçekleştirilen üretimin planlanan üretime oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Üretim", related_other_process: "", indicator_tag: "Üretim, Plan, Uyum", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Vadesi geçmiş kredi sayısı", indicator_definition: "Vadesi geçmiş kredi sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Finans", related_other_process: "", indicator_tag: "Kredi, Finans, Vade", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Vadesi geçmiş kredilerin ortalama değeri", indicator_definition: "Vadesi geçmiş kredilerin ortalama değeri.", direction: "Azalması İyi", measurement: "Para", related_process: "Finans", related_other_process: "", indicator_tag: "Kredi, Finans, Vade", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Vadesi geçmiş kredilerin toplam değeri", indicator_definition: "Vadesi geçmiş kredilerin toplam değeri.", direction: "Azalması İyi", measurement: "Para", related_process: "Finans", related_other_process: "", indicator_tag: "Kredi, Finans, Vade", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Yatırım Getirisi (ROI)", indicator_definition: "Yapılan yatırımın ne kadar getiri sağladığını gösteren oran.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Arge", related_other_process: "", indicator_tag: "ROI, Yatırım, Getiri", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Yeniden açılan olayların yüzdesi", indicator_definition: "Çözüldü olarak kapatılan ancak daha sonra yeniden açılmak zorunda kalınan IT olaylarının yüzdesi.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "IT, Olay, Helpdesk", indicator_related_management_system: "ISO 27001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Yetersiz Kapasiteden Kaynaklanan Olay Sayısı", indicator_definition: "Yetersiz kapasite nedeniyle üretimin durduğu olay sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Üretim", related_other_process: "", indicator_tag: "Kapasite, Üretim, Duruş", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Zamanında teslimat oranı (OTIF)", indicator_definition: "Siparişlerin belirlenen zamanda ve tam miktarda teslim edilme yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "OTIF, Teslimat, Lojistik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İş kazası kayıp iş günü sayısı", indicator_definition: "İş kazaları nedeniyle kaybedilen toplam iş günü sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "", indicator_tag: "Kaza, İSG, Kayıp İş Günü", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ramak kala olay sayısı", indicator_definition: "İş kazasına dönüşmeden önce tespit edilen ramak kala (near miss) olay sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "", indicator_tag: "Ramak Kala, İSG, Near Miss", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Kişisel koruyucu donanım uyum oranı", indicator_definition: "Çalışanların kişisel koruyucu donanım (KKD) kullanım kurallarına uyma oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "", indicator_tag: "KKD, İSG, Uyum", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Acil durum tatbikat sayısı", indicator_definition: "Belirli bir dönemde gerçekleştirilen acil durum tatbikatı sayısı.", direction: "Artması İyi", measurement: "Sayı", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "", indicator_tag: "Acil Durum, Tatbikat, İSG", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "IT güvenlik olayı sayısı", indicator_definition: "Belirli bir dönemde tespit edilen IT güvenlik ihlali sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "IT Güvenliği, Siber, Olay", indicator_related_management_system: "ISO 27001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Helpdesk çözüm oranı (FCR)", indicator_definition: "IT yardım masasına ilk başvuruda çözülen taleplerin yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "FCR, Helpdesk, IT", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "BT yatırımlarının gelire oranı", indicator_definition: "Toplam BT yatırımlarının gelire oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "BT, Yatırım, Gelir", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Yenilik oranı", indicator_definition: "Yeni ürün ve süreçlere yapılan Ar-Ge yatırımlarının toplam gelire oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Arge", related_other_process: "", indicator_tag: "Ar-Ge, İnovasyon, Yenilik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Patent başvuru sayısı", indicator_definition: "Belirli bir dönemde yapılan patent başvurularının sayısı.", direction: "Artması İyi", measurement: "Sayı", related_process: "Arge", related_other_process: "", indicator_tag: "Patent, Ar-Ge, IP", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ürün geliştirme süresi (TTM)", indicator_definition: "Bir ürünün fikir aşamasından pazara sunulmasına kadar geçen süre.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Arge", related_other_process: "", indicator_tag: "TTM, Ar-Ge, Ürün Geliştirme", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Müşteri edinme maliyeti (CAC)", indicator_definition: "Yeni bir müşteriyi kazanmak için harcanan ortalama maliyet.", direction: "Azalması İyi", measurement: "Para", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "CAC, Müşteri, Pazarlama", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Müşteri yaşam boyu değeri (CLV)", indicator_definition: "Bir müşterinin şirketle ilişkisi süresince sağladığı toplam değer.", direction: "Artması İyi", measurement: "Para", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "CLV, LTV, Müşteri, Değer", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Pazar payı", indicator_definition: "Şirketin toplam pazar içindeki satış yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Pazar Payı, Satış, Rekabet", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Dönüşüm oranı", indicator_definition: "Satış sürecinde potansiyel müşterinin gerçek müşteriye dönüşme oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Dönüşüm, Satış, CRM", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Üretim kapasite kullanım oranı", indicator_definition: "Fiili üretimin maksimum teorik üretim kapasitesine oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Üretim", related_other_process: "", indicator_tag: "Kapasite, Üretim, Kullanım", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Enerji tüketimi başına üretim", indicator_definition: "Birim enerji tüketimine karşılık üretilen ürün miktarı.", direction: "Artması İyi", measurement: "Sayı", related_process: "Üretim", related_other_process: "Çevre", indicator_tag: "Enerji, Üretim, Verimlilik", indicator_related_management_system: "ISO 14001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Hurda oranı", indicator_definition: "Üretim sürecinde hurda olan malzemenin toplam malzemeye oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Üretim", related_other_process: "", indicator_tag: "Hurda, Kalite, Üretim", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Yeniden işleme oranı", indicator_definition: "Kalite uygunsuzluğu nedeniyle yeniden işlem gerektiren ürünlerin yüzdesi.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Kalite", related_other_process: "Üretim", indicator_tag: "Yeniden İşleme, Kalite, Hata", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Müşteriye zamanında teslimat oranı", indicator_definition: "Müşterilere söz verilen tarihte yapılan teslimatların oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Tedarik Zinciri", related_other_process: "Satış ve Pazarlama", indicator_tag: "Teslimat, Müşteri, Lojistik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Nakit akış oranı", indicator_definition: "Operasyonel nakit akışının kısa vadeli borçlara oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Finans", related_other_process: "", indicator_tag: "Nakit, Akış, Finans", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Cari oran", indicator_definition: "Dönen varlıkların kısa vadeli borçlara oranı.", direction: "Artması İyi", measurement: "Sayı", related_process: "Finans", related_other_process: "", indicator_tag: "Cari Oran, Likidite, Finans", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Borç/Özsermaye oranı", indicator_definition: "Toplam borcun özsermayeye oranı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Finans", related_other_process: "", indicator_tag: "Borç, Özsermaye, Kaldıraç", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Tahsilat süresi (DSO)", indicator_definition: "Satışlar yapıldıktan sonra alacakların tahsil edilmesi için geçen ortalama gün sayısı.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Finans", related_other_process: "", indicator_tag: "DSO, Tahsilat, Alacak", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ödeme süresi (DPO)", indicator_definition: "Şirketin tedarikçilere ödeme yapması için geçen ortalama gün sayısı.", direction: "Artması İyi", measurement: "Zaman", related_process: "Finans", related_other_process: "Tedarik Zinciri", indicator_tag: "DPO, Ödeme, Borç", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Bütçe sapma oranı", indicator_definition: "Gerçekleşen harcamaların bütçelenen harcamalara göre sapma yüzdesi.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Finans", related_other_process: "", indicator_tag: "Bütçe, Sapma, Finans", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Su tüketimi", indicator_definition: "Belirli bir dönemde tüketilen toplam su miktarı.", direction: "Azalması İyi", measurement: "Ton", related_process: "Çevre", related_other_process: "", indicator_tag: "Su, Çevre, Kaynak", indicator_related_management_system: "ISO 14001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Enerji tüketimi", indicator_definition: "Belirli bir dönemde tüketilen toplam enerji miktarı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Çevre", related_other_process: "Üretim", indicator_tag: "Enerji, Çevre, Tüketim", indicator_related_management_system: "ISO 14001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Atık geri dönüşüm oranı", indicator_definition: "Geri dönüştürülen atıkların toplam atık miktarına oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Çevre", related_other_process: "", indicator_tag: "Atık, Geri Dönüşüm, Çevre", indicator_related_management_system: "ISO 14001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Tehlikeli atık miktarı", indicator_definition: "Belirli bir dönemde oluşturulan tehlikeli atık miktarı.", direction: "Azalması İyi", measurement: "Ton", related_process: "Çevre", related_other_process: "", indicator_tag: "Tehlikeli Atık, Çevre", indicator_related_management_system: "ISO 14001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çevresel eğitim tamamlama oranı", indicator_definition: "Çevre yönetimi eğitimlerini tamamlayan çalışanların yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Çevre", related_other_process: "İnsan Kaynakları", indicator_tag: "Çevre, Eğitim, ISO 14001", indicator_related_management_system: "ISO 14001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İSG eğitimi tamamlama oranı", indicator_definition: "İş sağlığı ve güvenliği eğitimlerini tamamlayan çalışanların yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "İnsan Kaynakları", indicator_tag: "İSG, Eğitim, Güvenlik", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Risk değerlendirme kapsamı", indicator_definition: "Risk değerlendirmesi tamamlanan iş süreçlerinin toplam iş süreçlerine oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "", indicator_tag: "Risk, Değerlendirme, İSG", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İşyeri güvenlik teftişi sayısı", indicator_definition: "Belirli bir dönemde gerçekleştirilen işyeri güvenlik teftiş sayısı.", direction: "Artması İyi", measurement: "Sayı", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "", indicator_tag: "Teftiş, İSG, Güvenlik", indicator_related_management_system: "ISO 45001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Çalışan başına sağlık maliyeti", indicator_definition: "Çalışan başına düşen toplam sağlık harcaması.", direction: "Azalması İyi", measurement: "Para", related_process: "İş Sağlığı ve Güvenliği", related_other_process: "İnsan Kaynakları", indicator_tag: "Sağlık, Maliyet, İSG", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Müşteri şikayet çözüm süresi", indicator_definition: "Müşteri şikayetlerinin ortalama çözüm süresi.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Kalite", related_other_process: "Satış ve Pazarlama", indicator_tag: "Şikayet, Kalite, Çözüm", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Düzeltici faaliyet kapatma oranı", indicator_definition: "Açılan düzeltici faaliyetlerin zamanında kapatılma yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Kalite", related_other_process: "", indicator_tag: "CAPA, Düzeltici Faaliyet, Kalite", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İç uygunsuzluk sayısı", indicator_definition: "İç kalite kontrol süreçlerinde tespit edilen uygunsuzluk sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Kalite", related_other_process: "", indicator_tag: "Uygunsuzluk, Kalite, İç Kontrol", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Dış uygunsuzluk sayısı", indicator_definition: "Müşteri veya dış denetimlerden gelen uygunsuzluk sayısı.", direction: "Azalması İyi", measurement: "Sayı", related_process: "Kalite", related_other_process: "", indicator_tag: "Uygunsuzluk, Kalite, Dış Denetim", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Proses yeterlilik indeksi (Cpk)", indicator_definition: "Üretim sürecinin kalite gereksinimlerini karşılama kapasitesini ölçen istatistiksel gösterge.", direction: "Artması İyi", measurement: "Sayı", related_process: "Kalite", related_other_process: "Üretim", indicator_tag: "Cpk, Proses Yeterlilik, SPC", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Satın alma döngü süresi", indicator_definition: "Satın alma talebinden tedarikçi seçimine kadar geçen ortalama süre.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Satın Alma, Tedarik, Süre", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Tedarikçi kalite uyumu oranı", indicator_definition: "Kalite standartlarını karşılayan tedarikçilerin toplam tedarikçilere oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Tedarik Zinciri", related_other_process: "Kalite", indicator_tag: "Tedarikçi, Kalite, Uyum", indicator_related_management_system: "ISO 9001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Depo doluluk oranı", indicator_definition: "Kullanılan depo alanının toplam depo kapasitesine oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Depo, Stok, Lojistik", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Gümrük işlem süresi", indicator_definition: "İthalat veya ihracat için gümrük işlemlerinin tamamlanma süresi.", direction: "Azalması İyi", measurement: "Zaman", related_process: "Tedarik Zinciri", related_other_process: "", indicator_tag: "Gümrük, Lojistik, İthalat", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Aktif proje sayısı", indicator_definition: "Belirli bir dönemde aktif olarak yürütülen Ar-Ge proje sayısı.", direction: "Artması İyi", measurement: "Sayı", related_process: "Arge", related_other_process: "", indicator_tag: "Proje, Ar-Ge, Aktif", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Ar-Ge personel oranı", indicator_definition: "Ar-Ge departmanında çalışan personel sayısının toplam personele oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Arge", related_other_process: "İnsan Kaynakları", indicator_tag: "Ar-Ge, Personel, İnovasyon", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Başarılı ürün lansmanı sayısı", indicator_definition: "Belirli bir dönemde başarıyla pazara sunulan yeni ürün sayısı.", direction: "Artması İyi", measurement: "Sayı", related_process: "Arge", related_other_process: "Satış ve Pazarlama", indicator_tag: "Lansman, Ürün, Ar-Ge", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Proje bütçe sapması", indicator_definition: "Ar-Ge projelerinde gerçekleşen harcamaların bütçeye göre sapma yüzdesi.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Arge", related_other_process: "Finans", indicator_tag: "Bütçe, Sapma, Proje", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İşe alım maliyeti", indicator_definition: "Her yeni işe alım için harcanan ortalama maliyet.", direction: "Azalması İyi", measurement: "Para", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "İşe Alım, Maliyet, İK", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Performans değerlendirme tamamlama oranı", indicator_definition: "Planlanan performans değerlendirmelerinin tamamlanma yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Performans, Değerlendirme, İK", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Eğitim yatırımı oranı", indicator_definition: "Eğitime yapılan yatırımın toplam personel maliyetine oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Eğitim, Yatırım, İK", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "İç terfi oranı", indicator_definition: "Açık pozisyonların iç terfiyle doldurulma yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Terfi, İK, Kariyer", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Cinsiyet çeşitlilik oranı", indicator_definition: "Organizasyondaki kadın çalışanların toplam çalışanlara oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "İnsan Kaynakları", related_other_process: "", indicator_tag: "Çeşitlilik, Cinsiyet, İK", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Dijital dönüşüm olgunluk skoru", indicator_definition: "Organizasyonun dijital dönüşüm süreçlerindeki olgunluk seviyesi.", direction: "Artması İyi", measurement: "Puan", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "Dijital, Dönüşüm, BT", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Yazılım lisans uyum oranı", indicator_definition: "Lisanslı yazılım kullanım kurallarına uyum oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "Lisans, Yazılım, Uyum", indicator_related_management_system: "ISO 27001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Veri yedekleme başarı oranı", indicator_definition: "Başarılı şekilde tamamlanan yedekleme işlemlerinin yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "Yedekleme, IT, Veri", indicator_related_management_system: "ISO 27001", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Kullanıcı memnuniyet skoru (IT)", indicator_definition: "IT hizmetlerinden duydukları memnuniyete göre kullanıcı skoru.", direction: "Artması İyi", measurement: "Puan", related_process: "Bilgi Teknolojileri", related_other_process: "", indicator_tag: "Kullanıcı Memnuniyeti, IT, Helpdesk", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "EBITDA marjı", indicator_definition: "Faiz, vergi, amortisman öncesi karın gelire oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Finans", related_other_process: "", indicator_tag: "EBITDA, Kar Marjı, Finans", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Brüt kar marjı", indicator_definition: "Brüt karın net satışlara oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Finans", related_other_process: "", indicator_tag: "Brüt Kar, Marj, Finans", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Alacak devir hızı", indicator_definition: "Net satışların ortalama alacaklara oranı.", direction: "Artması İyi", measurement: "Sayı", related_process: "Finans", related_other_process: "", indicator_tag: "Alacak, Devir, Finans", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Aktif karlılık oranı (ROA)", indicator_definition: "Net karın toplam aktiflere oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Finans", related_other_process: "", indicator_tag: "ROA, Karlılık, Finans", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Özsermaye karlılık oranı (ROE)", indicator_definition: "Net karın özsermayeye oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Finans", related_other_process: "", indicator_tag: "ROE, Karlılık, Özsermaye", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Pazarlama harcaması oranı", indicator_definition: "Pazarlama harcamalarının toplam gelire oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "Finans", indicator_tag: "Pazarlama, Harcama, ROI", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Dijital kanal satış oranı", indicator_definition: "Dijital kanallardan gerçekleşen satışların toplam satışlara oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "Bilgi Teknolojileri", indicator_tag: "Dijital, E-Ticaret, Satış", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Sosyal medya etkileşim oranı", indicator_definition: "Sosyal medya paylaşımlarının aldığı etkileşimin (beğeni, yorum, paylaşım) toplam takipçilere oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Satış ve Pazarlama", related_other_process: "", indicator_tag: "Sosyal Medya, Etkileşim, Pazarlama", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Bakım maliyetinin varlık değerine oranı", indicator_definition: "Toplam bakım maliyetinin ilgili varlığın değerine oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Bakım", related_other_process: "Finans", indicator_tag: "Bakım, Maliyet, Varlık", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Acil bakım oranı", indicator_definition: "Acil (plansız) bakımların toplam bakımlara oranı.", direction: "Azalması İyi", measurement: "Yüzde", related_process: "Bakım", related_other_process: "", indicator_tag: "Acil Bakım, Bakım, Plansız", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Bakım iş emri tamamlama oranı", indicator_definition: "Açılan bakım iş emirlerinin zamanında tamamlanma yüzdesi.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Bakım", related_other_process: "", indicator_tag: "İş Emri, Bakım, Tamamlama", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
  { indicator_name: "Yedek parça stok isabet oranı", indicator_definition: "Bakım anında ihtiyaç duyulan yedek parçanın stokta bulunma oranı.", direction: "Artması İyi", measurement: "Yüzde", related_process: "Bakım", related_other_process: "Tedarik Zinciri", indicator_tag: "Yedek Parça, Stok, Bakım", indicator_related_management_system: "", constituent_name: "Pedasoft", organization_name: "Pedasoft", is_default: true, is_accepted: true },
];

async function seed() {
  console.log(`Seeding ${KPI_DATA.length} KPIs...`);

  // Insert in batches of 20
  const batchSize = 20;
  let inserted = 0;

  for (let i = 0; i < KPI_DATA.length; i += batchSize) {
    const batch = KPI_DATA.slice(i, i + batchSize);
    const { error } = await supabase.from("indicators").insert(
      batch.map((kpi) => ({
        ...kpi,
        is_deleted: false,
        is_confirm_deleted: false,
      }))
    );

    if (error) {
      console.error(`Batch ${i / batchSize + 1} error:`, error.message);
    } else {
      inserted += batch.length;
      console.log(`✓ ${inserted}/${KPI_DATA.length} KPI eklendi`);
    }
  }

  console.log(`\nSeed tamamlandı! ${inserted} KPI Supabase'e aktarıldı.`);
}

seed().catch(console.error);
